language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --no-binary numpy --upgrade numpy
  - pip install -r requirements.txt
# command to run tests
script: python realtime_facenet.py